name: Node.js CI

on:
  push:
  pull_request:

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm test
